version: "3.6"
services:
  wildfly:
    build: ./wildfly-16.0.0.Final
    environment:
      JBOSS_HOST: 0.0.0.0
    command:
      - "/bin/bash"
      - "/src/bin/standalone.sh"
      - "-b"
      - "0.0.0.0"
      - "-bmanagement=0.0.0.0"
    ports:
      - '127.0.0.1:8080:8080' 
  qa:
    build: ./qa_dev_challenge/qa
    command: ./wait-for wildfly:8080 -- pytest
    depends_on:
      - wildfly

